# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 10:31
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatelove', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations_required',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('Money_required', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(null=True),
        ),
    ]
